# Web Scraping com Selenium
Nesta aula iremos criar uma **automação na internet** utilizando a biblioteca Selenium

#### Passo 1: Instalar biblioteca

In [2]:
# Remova o comentário(#) da linha abaixo caso esteja executando este script pela primeira vez
%pip install --upgrade selenium
%pip install webdriver-manager

Requirement already satisfied: selenium in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (4.48.0)
Requirement already satisfied: certifi>=2026.2.25 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from selenium) (2026.7.22)
Requirement already satisfied: trio<1.0,>=0.31.0 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from selenium) (0.34.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in C:\Users\49048057809\AppData\Roaming\Python\Python314\site-packages (from selenium) (4.16.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.7.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (26.1.0)
Requirement already satisfied: sortedcontainers in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.19)
Requirement already satisfied: outcome in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.1.1)
Requirement already satisfied: wsproto>=0.14 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (3.0)
Requirement already satisfied: h11<1,>=0.16.0 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: webdriver-manager in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (4.1.2)
Requirement already satisfied: requests in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from webdriver-manager) (2.34.2)
Requirement already satisfied: python-dotenv in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from webdriver-manager) (1.2.3)
Requirement already satisfied: packaging in C:\Users\49048057809\AppData\Roaming\Python\Python314\site-packages (from webdriver-manager) (26.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->webdriver-manager) (3.5.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->webdriver-manager) (3.19)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->webdriver-manager) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\49048057809\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from requests->webdriver-manager) (2026.7.22)
Note: you may need to restart the kernel to use updated packages.

#### Passo 2: Importar bibliotecas

In [3]:
import pandas as pd

# Módulo que fornece a classe principal para criar e controlar instâncias do navegador
from selenium import webdriver 

# Módulo para localização de elementos na página
from selenium.webdriver.common.by import By

# Módulo para simular as teclas
from selenium.webdriver.common.keys import Keys

#### Passo 3: Criar navegador

In [4]:
driver = webdriver.Chrome()  # Cria uma instância do navegador Chrome

#### Passo 4: Acessar site

In [5]:
# url: 'https://pubmed.ncbi.nlm.nih.gov/

driver.get('https://pubmed.ncbi.nlm.nih.gov/')  # Abre a página do PubMed

#### Passo 5: Fechar navegador

In [6]:
driver.quit()  # Fecha o navegador

#### Passo 6: Acessar site e obter elementos elementos html

Para obter os elementos do site existem basicamente dois comandos
- find_element() -> Para acessar apenas um elemento
- find_elements() -> Para acessar vários elementos de uma vez

A partir destes comandos podemos usar vários métodos de seleção, por:
- **tag_name:** Localiza elementos com nome de tag correspondente ao valor de pesquisa
- **id:** Localiza elementos com atributo ID correspondente ao valor de pesquisa
- **class_name:** Localiza elementos com nome de classe que contém o valor de pesquisa (nomes de classe compostos não são permitidos)
- **css_selector:** Localiza elementos que correspondem a um seletor CSS
- **name:** Localiza elementos com atributo NAME correspondente ao valor de pesquisa
- **xpath:** Localiza elementos que correspondem a uma empressão XPath
- **link_text:** Localiza elementos âncora em que o texto visível corresponde ao valor de pesquisa
- **partial link text:** Localiza elementos âncora em que o texto visível contém o valor de pesquisa. Se vários elementos forem correspondentes, apenas o primeiro será selecionado

Após selecionar os elementos podemos executar algumas ações:
- **click():** Simula um clique do mouse em um elemento. Exemplo: elemento.click().
- **send_keys('Text'):** Insira texto em um campo. Exemplo: elemento.send_keys("texto a ser inserido").
- **clear():** Remova o texto existente em um campo de texto. Exemplo: elemento.clear().
- **submit():** Envie um formulário. Exemplo: elemento.submit().
- **select_by_visible_text('Texto'):** Selecione uma opção em uma lista suspensa por texto visível. Exemplo: elemento.select_by_visible_text("Opção Desejada").
- **Keys.ENTER:** Simula a tecla Enter. Pode ser usado em combinação com send_keys()para enviar formulários ou em outras situações que desative a tecla Enter. Exemplo: elemento.send_keys(Keys.ENTER).

#### 6.1: Criar navegador e acessar site

In [7]:
driver = webdriver.Chrome()
driver.get('https://pubmed.ncbi.nlm.nih.gov/')

#### 6.2: Selecionar o campo de busca pelo id

In [9]:
campo_busca = driver.find_element(By.ID, "id_term")  # Localiza o campo de busca pelo ID

#### 6.3: Escrever um texto no campo de busca

In [10]:
campo_busca.send_keys("Pokemon")

#### 6.4: Clicar no Botão Pesquisar

In [11]:
driver.find_element(By.CLASS_NAME, "search-btn").click()

#### 6.5: Fechar navegador

In [12]:
driver.quit()

#### Passo 7: Obter elementos dos resultados de busca

In [29]:
driver = webdriver.Chrome()
driver.get('https://pubmed.ncbi.nlm.nih.gov/')
campo_busca = driver.find_element(By.ID, "id_term") 
campo_busca.send_keys("Pokemon", Keys.ENTER)

resultados = driver.find_elements(By.CLASS_NAME, "docsum-content")

print("Total de resultados encontrados:", len(resultados))

Total de resultados encontrados: 10

#### 7.1: Listar o título de todos os resultados

In [30]:

lista_de_titulos = []
for i in resultados:
    lista_de_titulos.append(i.find_element(By.CLASS_NAME, "docsum-title").text)

lista_de_titulos

['Primary Care: Its Pokemon Moment.',
 'Impact of Pokemon Go on Physical Activity: A Systematic Review and Meta-Analysis.',
 'Effects of Pokemon GO on Physical Activity and Psychological and Social Outcomes: A Systematic Review.',
 'Influence of Pokemon GO on Physical Activity and Psychosocial Well-Being in Children and Adolescents: Systematic Review.',
 'Going Forward with Pokemon Go.',
 'Pokemon contagion.',
 'Random forests, sound symbolism and Pokemon evolution.',
 'Pokemon Go and augmented virtual reality games: a cautionary commentary for parents and pediatricians.',
 'Pokemon inhibits Bim transcription to promote the proliferation, anti-anoikis, invasion, histological grade, and dukes stage of colorectal neoplasms.',
 'Pokemon GO and Physical Activity in Asia: Multilevel Study.']

#### 7.2: Listar o link de todos os resultados

In [31]:
lista_de_links = []
for j in resultados:
    lista_de_links.append(j.find_element(By.CLASS_NAME, "docsum-title").get_attribute("href"))
lista_de_links

['https://pubmed.ncbi.nlm.nih.gov/38556037/',
 'https://pubmed.ncbi.nlm.nih.gov/31836333/',
 'https://pubmed.ncbi.nlm.nih.gov/33922978/',
 'https://pubmed.ncbi.nlm.nih.gov/37955949/',
 'https://pubmed.ncbi.nlm.nih.gov/30568365/',
 'https://pubmed.ncbi.nlm.nih.gov/11811868/',
 'https://pubmed.ncbi.nlm.nih.gov/36598905/',
 'https://pubmed.ncbi.nlm.nih.gov/27479151/',
 'https://pubmed.ncbi.nlm.nih.gov/39095579/',
 'https://pubmed.ncbi.nlm.nih.gov/29907559/']

#### 7.3: Acessar um dos links

In [32]:
driver.get(lista_de_links[0])

## Exercício 1
Acesse um dos links da lista e obtenha:

##### 1) Título

In [33]:
titulo = driver.find_element(By.CLASS_NAME, "heading-title").text
print(titulo)

Primary Care: Its Pokemon Moment

##### 2) Autores

In [18]:
autores = driver.find_element(By.CLASS_NAME, "authors").text
print(autores)

Bryan Becker  1

##### 3) Ano de publicação

In [19]:
ano = driver.find_element(By.CLASS_NAME, "cit").text
print(ano)

2024 Jul;137(7):577-581.

##### 4) DOI

In [20]:
doi = driver.find_element(By.CLASS_NAME, "identifier.doi").text
print(doi)

DOI: 10.1016/j.amjmed.2024.03.020

##### 5) Tipo de publicação

In [21]:
tipo_publicação = driver.find_element(By.CLASS_NAME, "publication-type").text
print(tipo_publicação)

Review

##### 6) Resumo

In [22]:
resumo_publicacao = driver.find_element(By.CLASS_NAME, "abstract-content.selected").text
print(resumo_publicacao)

Primary care in the United States is undergoing bursts of evolution in response to health system stresses, changing demographics, and expansion of risk and value-based reimbursement structures. The impact of primary care remains substantive and associated with improved population health. However, the spectrum of services, the nature of the physicians involved and new ways of including the patient in her, or his own care suggests that a new definition of primary care be considered, and patient expectations be heeded and understood. Evolutionary bursts yield new traits and in primary care, they are spawning new care models with significant implications for general internal medicine, internal medicine/pediatrics trained individuals and medicine subspecialties given the focus of these models on Medicare Advantage. Ultimately, changes in reimbursement and creative incentives will be two factors among many that will solidify the next stage of primary care in the United States.

##### 7) Link de acesso (como registro de referência)

## Exercício 2: Automatizar o processo anterior para todos os links da lista
Extrair as informações abaixo de cada um dos links obtidos

- Título
- Autores
- Ano
- DOI
- Tipo de publicação
- Resumo
- Link

### Armazene todas as informações em um DataFrame

#### 1) Criar tabela para armazenar dados

In [36]:
colunas = [
    "titulo",
    "autores",
    "ano",
    "doi",
    "tipo_publicacao",
    "resumo"
]

tabela = pd.DataFrame(columns=colunas)

tabela

Empty DataFrame
Columns: [titulo, autores, ano, doi, tipo_publicacao, resumo]
Index: []

#### 2) Obter dados dos links e armazenar na tabela

In [38]:
lista_dados = []

for i in lista_de_links:
    try:
        titulo = driver.find_element(By.CLASS_NAME, "heading-title").text
    except:
        titulo = "N/A"
    try:
        autores = driver.find_element(By.CLASS_NAME, "authors").text
    except:
        autores = "N/A"
    try:
        ano = driver.find_element(By.CLASS_NAME, "cit").text
    except:
        ano = "N/A"
    try:
        doi = driver.find_element(By.CLASS_NAME, "identifier.doi").text 
    except:
        doi = "N/A"
    try:
        tipo_publicacao = driver.find_element(By.CLASS_NAME, "publication-type").text
    except:
        tipo_publicacao = "N/A"
    try:
        resumo_publicacao = driver.find_element(By.CLASS_NAME, "abstract-content.selected").text
    except:
        resumo_publicacao = "N/A"

    lista_dados.append(
        [titulo, autores, ano, doi, tipo_publicacao, resumo_publicacao]
    )

tabela = pd.DataFrame(lista_dados, columns=["Título", "Autores", "Ano", "DOI", "Tipo", "Resumo"]) # Ajuste os nomes das colunas se necessário

#### 3) Visualizar tabela

In [39]:
tabela

,Título,Autores,Ano,DOI,Tipo,Resumo
0,Primary Care: Its Pokemon Moment,Bryan Becker 1,2024 Jul;137(7):577-581.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...
1,Primary Care: Its Pokemon Moment,Bryan Becker 1,2024 Jul;137(7):577-581.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...
2,Primary Care: Its Pokemon Moment,Bryan Becker 1,2024 Jul;137(7):577-581.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...
3,Primary Care: Its Pokemon Moment,Bryan Becker 1,2024 Jul;137(7):577-581.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...
4,Primary Care: Its Pokemon Moment,Bryan Becker 1,2024 Jul;137(7):577-581.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...
5,Primary Care: Its Pokemon Moment,Bryan Becker 1,2024 Jul;137(7):577-581.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...
6,Primary Care: Its Pokemon Moment,Bryan Becker 1,2024 Jul;137(7):577-581.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...
7,Primary Care: Its Pokemon Moment,Bryan Becker 1,2024 Jul;137(7):577-581.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...
8,Primary Care: Its Pokemon Moment,Bryan Becker 1,2024 Jul;137(7):577-581.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...
9,Primary Care: Its Pokemon Moment,Bryan Becker 1,2024 Jul;137(7):577-581.,DOI: 10.1016/j.amjmed.2024.03.020,Review,Primary care in the United States is undergoin...

#### 4) Exportar DataFrame para Excel

In [41]:
%pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   ---------------------------------------- 0/2 [et-xmlfile]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [42]:
exportar_excel = tabela.to_excel("tabela_pubmed.xlsx", index=False)